export const GET_BUDGET = "GET_BUDGET";
export const GET_BUDGET_SUCCESS = "GET_BUDGET_SUCCESS";
export const GET_BUDGET_FAIL = "GET_BUDGET_FAIL";

export const EDIT_BUDGET = "EDIT_BUDGET";
export const EDIT_BUDGET_SUCCESS = "EDIT_BUDGET_SUCCESS";
export const EDIT_BUDGET_FAIL = "EDIT_BUDGET_FAIL";
